---
title: "abuyog_data_insect_plant_hopper"
author: "Mihkail Cornell"
date: "2023-09-02"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
hopper_df_abuyog <- 
  insect_raw %>%
  select(FarmID, `Collection Date`, Province, Municipality, `Crop Stage`, Treatment, `Corn Type`, Variety, contains("Corn Plant Hopper - Damage Rating")) %>%
  filter(Municipality == "Abuyog")

# convert date format
hopper_df_abuyog$collect_date <- 
  as.Date(hopper_df_abuyog$`Collection Date`, "%B %d, %Y")

hopper_dmg_abuyog <-
  hopper_df_abuyog %>% 
  mutate(Year = year(collect_date), Month = month(collect_date))

# merged with monthly average weather parameters
classification_dmg <- function(x) {ordered(x, levels = c("No", "Light", "Moderate", "Severe", "High"))}


rank_rating <- c(1, 3, 5, 7, 9)
names(rank_rating) <- c("No", "Light", "Moderate", "Severe", "High")
ranked_class <- rank(rank_rating)
factor(rank_rating, ordered=TRUE)


getmode <- function(v) {
  uniqv <- unique(v)
  uniqv[which.max(tabulate(match(v, uniqv)))]
}

hopper_joined_abuyog <-
  hopper_dmg_abuyog %>% 
  left_join(monthly_averages, by=c('Year', 'Month')) %>%
  # mutate_at(c(9:28), as.factor) %>%
  mutate(across(contains("Corn Plant Hopper - Damage Rating "), 
         ~ case_when( . == 1 ~ "No",
                      . == 3 ~ "Light",
                      . == 5 ~ "Moderate",
                      . == 7 ~ "Severe",
                      . == 9 ~ "High"), 
         .names="Class_Infest_{.col}")) %>%
  mutate(across(contains("Class_Infest_Corn Plant Hopper - Damage Rating "), ~classification_dmg(.))) %>%
  # get the modal observation rating
   mutate(Mode_class_infest_hopper = getmode(c_across(contains("Class_Infest_Corn Plant Hopper - Damage Rating ")))) %>%
  # create ranks column
  mutate(Ranked_mode_classification = rank(Mode_class_infest_hopper))
```

```{r}
hopper_abuyog_parsed <-
    hopper_joined_abuyog %>% 
    select(Municipality, collect_date, Year, Month, `Crop Stage`, Treatment, `Corn Type`, Variety, Mode_class_infest_hopper, mean_temp:median_humid) %>%
    mutate(variety = case_when(str_detect(Variety, 'OPV') ~ "OPV White",
                               str_detect(Variety, "^[MmAaCcHhOo]") ~ "Macho F1",
                               str_detect(Variety, "^J") ~ "J505",
                               str_detect(Variety, "Native [Ww]hite") ~ "Native White",
                               str_detect(Variety, "^TINI") ~ "Tiniguib",
                               str_detect(Variety, "^G[LlUuTtIiNnOoUuSs]") ~ "Glutinous White",
                               str_detect(Variety, "^Y[EeLl]") ~ "Yellow Corn",
                               TRUE ~ Variety)) %>% 
    mutate_if(is.character, as.factor) %>%
    select(-Variety)
```


