---
title: "maasin_insect_data_plant_hopper"
author: "Mihkail Cornell"
date: "2023-09-04"
output: html_document
---

```{r}
hopper_df_maasin <- 
  insect_raw %>%
  select(FarmID, `Collection Date`, Province, Municipality, `Crop Stage`, Treatment, `Corn Type`, Variety, contains("Corn Plant Hopper - Damage Rating")) %>%
  filter(Municipality == "Maasin City")

# convert date format
hopper_df_maasin$collect_date <- 
  as.Date(hopper_df_maasin$`Collection Date`, "%B %d, %Y")

hopper_dmg_maasin <-
  hopper_df_maasin %>% 
  mutate(Year = year(collect_date), Month = month(collect_date))

# merged with monthly average weather parameters
classification_dmg <- function(x) {ordered(x, levels = c("No", "Light", "Moderate", "Severe", "High"))}


rank_rating <- c(1, 3, 5, 7, 9)
names(rank_rating) <- c("No", "Light", "Moderate", "Severe", "High")
ranked_class <- rank(rank_rating)
factor(rank_rating, ordered=TRUE)


getmode <- function(v) {
  uniqv <- unique(v)data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABIAAAASCAYAAABWzo5XAAAAWElEQVR42mNgGPTAxsZmJsVqQApgmGw1yApwKcQiT7phRBuCzzCSDSHGMKINIeDNmWQlA2IigKJwIssQkHdINgxfmBBtGDEBS3KCxBc7pMQgMYE5c/AXPwAwSX4lV3pTWwAAAABJRU5ErkJggg==
  uniqv[which.max(tabulate(match(v, uniqv)))]
}

hopper_joined_maasin <-
  hopper_dmg_maasin %>% 
  left_join(monthly_averages, by=c('Year', 'Month')) %>%
  # mutate_at(c(9:28), as.factor) %>%
  mutate(across(contains("Corn Plant Hopper - Damage Rating "), 
         ~ case_when( . == 1 ~ "No",
                      . == 3 ~ "Light",
                      . == 5 ~ "Moderate",
                      . == 7 ~ "Severe",
                      . == 9 ~ "High"), 
         .names="Class_Infest_{.col}")) %>%
  mutate(across(contains("Class_Infest_Corn Plant Hopper - Damage Rating "), ~classification_dmg(.))) %>%
  # get the modal observation rating
   mutate(Mode_class_infest_hopper = getmode(c_across(contains("Class_Infest_Corn Plant Hopper - Damage Rating ")))) %>%
  # create ranks column
  mutate(Ranked_mode_classification = rank(Mode_class_infest_hopper))

hopper_joined_maasin$Variety %>% unique()
```

```{r}
hopper_maasin_parsed <-
    hopper_joined_maasin %>% 
    select(Municipality, 
           collect_date, 
           Year, 
           Month, 
           `Crop Stage`, 
           Treatment, 
           `Corn Type`, 
           Variety, 
           Mode_class_infest_hopper, mean_temp:median_humid) %>%
    mutate(variety = case_when(str_detect(Variety, '^(OPV White Var)') ~ "OPV White Var.6",
                               str_detect(Variety, "^([MmAaCcHhOo])") ~ "Macho F1",
                               str_detect(Variety, "(F[IiLlIiPpIiNnAa_ ]*)703") ~ "Filipina 703-HY",
                               str_detect(Variety, "^(J)") ~ "J505",
                               str_detect(Variety, "^([P|Pioneer])") ~ "Pioneer 266",
                               str_detect(Variety, "B9909G") ~ "B9909G",
                               str_detect(Variety, "^([IPB_VAR_6])") ~ "IPB_VAR_6",
                               str_detect(Variety, "^(B9899G)") ~ "B9899G",
                               str_detect(Variety, "^(Y[EeLl])") ~ "Yellow Corn",
                               str_detect(Variety, "^(NK6410)") ~ "NK6410 BT/GT-HY",
                               str_detect(Variety, "^(B118G)") ~ "B118G-Hybrid Yellow",
                               str_detect(Variety, "\\b(BioCorn)") ~ "BioCorn 108-Hybrid Yellow",
                               str_detect(Variety, "(([FIi])[l ĺ]*ipina 802|FILIPINA_802)") ~ "Filipina 802-HW",
                               str_detect(Variety, "T[IiNiGgUuIiBb]") ~ "Tiniguib",
                               str_detect(Variety, "Supreme 5150-H[YW]") ~ "Supreme 5150-HW",
                               
                               TRUE ~ Variety)) %>% 
    mutate_if(is.character, as.factor) %>%
    select(-Variety)

hopper_maasin_parsed$variety %>% unique()
```

```{r}
rank_mean_fn <- function(x) {ordered(x, levels = c("25_Below", "25_to_27", "27_Above"))}

hopper_maasin_rank_df <-
  hopper_joined_maasin |>
  mutate(rank_mean_temp = case_when(mean_temp > 27 ~ "27_Above", 
                                    mean_temp < 25 ~ "25_Below",
                                    TRUE ~ "25_to_27"),
         rank_mean_temp = rank_mean_fn(rank_mean_temp))

```

```{r}
cor.test(as.numeric(hopper_maasin_rank_df$Mode_class_infest_hopper), as.numeric(hopper_maasin_rank_df$rank_mean_temp), method="kendall")
```

















